[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Microscopy Glossary"
authors = [{name = "Caterina Strambio De Castillia", email = "caterina.strambio@umassmed.edu"}]
dynamic = ["version", "description"]
